name: Build vendor

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: none

      - name: Composer install (no dev)
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Pack vendor
        run: |
          zip -r vendor.zip vendor composer.lock composer.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor.zip
